I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 21, in script
    $ renpy.auto_forward(True)
  File "game/script.rpy", line 21, in <module>
    $ renpy.auto_forward(True)
AttributeError: module 'renpy.exports' has no attribute 'auto_forward'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 21, in script
    $ renpy.auto_forward(True)
  File "D:\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 21, in <module>
    $ renpy.auto_forward(True)
AttributeError: module 'renpy.exports' has no attribute 'auto_forward'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ChatWaifuL2D 2.0
Mon Apr  8 00:25:31 2024
