I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    e "[path]"
NameError: Name 'path' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    e "[path]"
  File "D:\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\renpy-8.2.1-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.2.1-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.2.1-sdk\renpy\character.py", line 1379, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "D:\renpy-8.2.1-sdk\renpy\character.py", line 1293, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "D:\renpy-8.2.1-sdk\renpy\character.py", line 1273, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\renpy-8.2.1-sdk\renpy\substitutions.py", line 368, in substitute
    s = interpolate(s, kwargs) # type: ignore
  File "D:\renpy-8.2.1-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "D:\renpy-8.2.1-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "D:\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "D:\renpy-8.2.1-sdk\renpy\substitutions.py", line 310, in __getitem__
    raise NameError("Name '{}' is not defined.".format(key))
NameError: Name 'path' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ChatWaifuL2D 2.0
Mon Apr  8 23:00:21 2024
